spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://patient-service:8000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
        - id: api-docs-patient-service
          uri: http://patient-service:8000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs

server:
  port: 8004