### Create Patient
POST http://localhost:8000/patients
Content-Type: application/json

{
    "name": "Mamadou Ba with billing account 4",
    "email": "test_with_billing4@example.com",
    "address": "123 Nouakchot Mauritanie",
    "dateOfBirth": "1995-09-09",
    "registeredDate": "2025-08-28"
}

###